<?php

//$Id$

// Copyright 2005 Khalid Baheyeldin http://2bits.com


/**
 * @file
 * Enables custom 404 (not found) and 403 (access denied) pages in Drupal
 * with no need for creating real nodes under taxonomies
 */

function _customerror_enum_errors() {
  // This is where the error codes and their default descriptions are
  // stored. Add here as necessary.
  $errors = array(
    404 => t('requested page not found'),
    403 => t('access denied')
    );

  return $errors;
}

function _customerror_fetch_error($error_code) {
  $errors = _customerror_enum_errors();

  $default_desc = t('unknown error: @error_code', array('@error_code' => $error_code));

  $r = $default_desc;

  foreach ($errors as $code => $desc) {
    if ($error_code == $code) {
      $r = $desc;
    }
  }
  return $r;
}

/**
 * Implementation of hook_help().
 */
function customerror_help($path, $arg) {
  switch ($path) {
    case 'admin/modules#description':
      $output = t('Enables the creation of custom error pages for 404 and 403 errors.');
      break;
    case 'admin/settings/customerr':
      $output = t('Enables the creation of custom error pages for 404 and 403 errors.');
      break;
  }
  return $output;
}

function customerror_admin_settings()
{
  $form = array(
    'customerror_form_description' => array(
      '#type' => 'markup',
      '#value' => t('Enter the error pages that will be seen by your visitors when they get the respective errors. You can enter any HTML text. You can point the users to the FAQ, inform them that you reorganized the site, ask them to report the error, login or register, ...etc.')
    )
  );

  $errors = _customerror_enum_errors();
  foreach($errors as $error_code => $error_desc) {
    $form['customerror_' . $error_code . '_title'] = array(
      '#type' => 'textfield',
      '#title' => t('Title for @error_code', array('@error_code' => $error_code)),
      '#default_value' => variable_get('customerror_' . $error_code . '_title', $error_desc),
      '#size' => 70,
      '#maxlength' => 70,
      '#description' => t('Title of @error_code error page', array('@error_code' => $error_code . ' error page')),
    );
    $form['customerror_' . $error_code] = array(
      '#type' => 'textarea',
      '#title' => t('Description for ') . $error_code,
      '#default_value' => variable_get('customerror_' . $error_code, $error_desc),
      '#rows' => 10,
      '#description' => t('This text will be displayed if a @error_code (@error_desc) error occurs.', array('@error_code' => $error_code, '@error_desc' => $error_desc)),
    );
    $form['customerror_' . $error_code . '_php'] = array(
      '#type' => 'checkbox',
      '#title' => t('Allow PHP code to be executed for @error_code', array( '@error_code' => $error_code)),
      '#default_value' => variable_get('customerror_' . $error_code . '_php', FALSE),
      '#description' => t('This allows you to include PHP code (enclosed in &lt;?php ?&gt; tags) for the @error_code (@error_desc) message. Note that this can be dangerous in some situations. Make sure that you are aware of the implications.', array('@error_code' => $error_code, '@error_desc' => $error_desc)),
    );
  }

  $form['customerror_redirect'] = array(
    '#type' => 'textarea',
    '#title' => t('Redirect list'),
    '#default_value' => variable_get('customerror_redirect', ''),
    '#rows' => 10,
    '#description' => t('These are custom redirect pairs, one per line. Each pair is a key which is a regular expression, and a destination path for it, separated by a space.'),
  );

  return system_settings_form($form);
}

function customerror_menu() {
  $items = array();

  $items['admin/settings/customerror'] = array(
    'title' => 'Custom error',
    'description' => 'Administer custom error.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('customerror_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['customerror'] = array(
    'title'    => 'customerror',
    'access callback'   => TRUE,
    'page callback' => 'customerror_page',
    'type'     => MENU_CALLBACK,
    'weight'   => 0 );

  return $items;
}

/**
* Implementation of hook_simpletest().
*/
function customerror_simpletest() {
  return array_keys(file_scan_directory(
    drupal_get_path('module', 'customerror') . '/tests', '\.test$'));
}

/**
 * Implementation of hook_page().
 */
function customerror_page() {
  $error_code = arg(1);

  switch($error_code) {
    case 403:
    case 404:
      customerror_check_redirect();
      drupal_set_title(variable_get('customerror_'. $error_code .'_title', _customerror_fetch_error($error_code)));
      $output = theme('customerror', $error_code, variable_get('customerror_' . $error_code, _customerror_fetch_error($error_code)));
      $output = (variable_get('customerror_' . $error_code . '_php', FALSE)) ? drupal_eval($output) : $output;
      break;
    default:
      drupal_set_title(t('undefined error: ') . $error_code);
      $output = _customerror_fetch_error($error_code);
      break;
  }
  return $output;
}

/**
 * Implementation of hook_theme().
 */
function customerror_theme() {
  return array(
    'customerror' => array(
      'arguments' => array('error_code', 'content')
    ),
  );
}

/**
 * Themeable function 
 */
function theme_customerror($error_code, $content) {
  return $content;
}

function customerror_user($op, $edit, $user) {
  switch($op) {
    case 'login':
      // Check if we have a destination saved in the session
      $destination = $_SESSION['destination'];
      if ($destination) {
        // If there is one, then set the REQUEST destination to it
        $_REQUEST['destination'] = $destination;
        // And clear the one in the session
        unset($_SESSION['destination']);
        // user.module then does a drupal_goto() for us after we return from here
      }
  }
}
function customerror_check_redirect() {
  $destination = $_REQUEST['destination'];
  if (isset($destination)) {
    $list = explode("\n", variable_get('customerror_redirect', ''));
    if (count($list)) {
      foreach($list as $item) {
        list($src, $dst) = explode(' ', $item);
        if (isset($src) && isset($dst)) {
          $src = str_replace("/", "\\/", $src);
          $dst = str_replace("\r", "", $dst);
          if (preg_match('/'. $src .'/', $destination)) {
            $_REQUEST['destination'] = $dst;
            drupal_goto($dst);
          }
        }
      }
    }
  }
}
